# TCL File Generated by Component Editor 12.0
# Thu Nov 29 09:10:34 EST 2012
# DO NOT MODIFY


# 
# mandelbrot_zoom_wrapper "mandelbrot_zoom_wrapper" v1.0
# null 2012.11.29.09:10:34
# 
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module mandelbrot_wrapper
# 
set_module_property NAME mandelbrot_zoom_wrapper
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME mandelbrot_zoom_wrapper
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mandelbrot_zoom_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mandelbrot_zoom_wrapper.v VERILOG PATH mandelbrot_zoom_wrapper.v
add_fileset_file mandelbrot_zoom.v VERILOG PATH mandelbrot_zoom.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clockreset
# 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0
set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1


# 
# connection point clockreset_reset
# 
add_interface clockreset_reset reset end
set_interface_property clockreset_reset associatedClock clockreset
set_interface_property clockreset_reset synchronousEdges DEASSERT
set_interface_property clockreset_reset ENABLED true

add_interface_port clockreset_reset csi_clockreset_reset reset Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clockreset
set_interface_property s1 associatedReset clockreset_reset
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitStates 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_address address Input 4
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_readdata readdata Output 32


# 
# connection point ACCEL
# 
add_interface ACCEL avalon start
set_interface_property ACCEL addressUnits SYMBOLS
set_interface_property ACCEL associatedClock clockreset
set_interface_property ACCEL associatedReset clockreset_reset
set_interface_property ACCEL burstOnBurstBoundariesOnly false
set_interface_property ACCEL doStreamReads false
set_interface_property ACCEL doStreamWrites false
set_interface_property ACCEL linewrapBursts false
set_interface_property ACCEL readLatency 1
set_interface_property ACCEL ENABLED true

add_interface_port ACCEL avm_ACCEL_readdata readdata Input 64
add_interface_port ACCEL avm_ACCEL_address address Output 32
add_interface_port ACCEL avm_ACCEL_writedata writedata Output 64
add_interface_port ACCEL avm_ACCEL_write write Output 1
add_interface_port ACCEL avm_ACCEL_read read Output 1
add_interface_port ACCEL avm_ACCEL_byteenable byteenable Output 8
add_interface_port ACCEL avm_ACCEL_waitrequest waitrequest Input 1

