/home/liang/Downloads/legup-3.0/llvm/lib/CompilerDriver/Release+Asserts/Main.o \
 /home/liang/Downloads/legup-3.0/llvm/lib/CompilerDriver/Release+Asserts/Main.d: \
 Main.cpp \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/CompilerDriver/AutoGenerated.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/CompilerDriver/BuiltinOptions.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/CommandLine.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/type_traits.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/Compiler.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/SmallVector.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/Twine.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/StringRef.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/DataTypes.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/CompilerDriver/CompilationGraph.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/CompilerDriver/Tool.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/CompilerDriver/Action.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/Casting.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/StringSet.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/StringMap.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/Allocator.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/AlignOf.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/MathExtras.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/SwapByteOrder.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/Path.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/PathV1.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/TimeValue.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/PathV2.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/SmallString.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/GraphTraits.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/CompilerDriver/Error.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/raw_ostream.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/FileSystem.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/system_error.h \
 /home/liang/Downloads/legup-3.0/llvm/include/llvm/Config/llvm-config.h

/home/liang/Downloads/legup-3.0/llvm/include/llvm/CompilerDriver/AutoGenerated.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/CompilerDriver/BuiltinOptions.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/CommandLine.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/type_traits.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/Compiler.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/SmallVector.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/Twine.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/StringRef.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/DataTypes.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/CompilerDriver/CompilationGraph.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/CompilerDriver/Tool.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/CompilerDriver/Action.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/Casting.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/StringSet.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/StringMap.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/Allocator.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/AlignOf.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/MathExtras.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/SwapByteOrder.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/Path.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/PathV1.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/TimeValue.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/PathV2.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/SmallString.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/ADT/GraphTraits.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/CompilerDriver/Error.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/raw_ostream.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/FileSystem.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Support/system_error.h:

/home/liang/Downloads/legup-3.0/llvm/include/llvm/Config/llvm-config.h:
